version: 1
type: "required_status_checks"
branches:
  - name: main
    required_checks:
      - "🛡️ Security CI (SAST / SCA / Secrets / DAST / Misconfig)"
      - "Deploy to VMware lab (Ansible + Docker Compose)"
    required_approvals: 1
    require_signed_commits: true
    enforce_admins: true
CODEOWNERS: |
  * @novaferrydianto

