name: "Vuln Bank – Security Scan Core"
description: "Authoritative security scan core: Secrets, SAST, SCA+EPSS/KEV, optional DAST, ASVS export"

inputs:
  run_dast:
    description: "Run DAST (true/false)"
    required: false
    default: "true"

  epss_threshold:
    description: "EPSS threshold"
    required: false
    default: "0.5"

  zap_fail_severity:
    description: "ZAP fail severity (e.g., HIGH, MEDIUM)"
    required: false
    default: "HIGH"

  dast_url:
    description: "Target URL for DAST readiness + ZAP"
    required: false
    default: "http://vuln-bank-dast:5000"

  dast_compose_file:
    description: "Compose file used for DAST stack"
    required: false
    default: "docker-compose.dast.yml"

  report_dir:
    description: "Report directory"
    required: false
    default: "security-reports"

  baseline_dir:
    description: "Baseline directory"
    required: false
    default: "security-baselines"

outputs:
  gate_failed:
    description: "true if any gate wrote gate_failed marker"
    value: ${{ steps.finalize.outputs.gate_failed }}

  asvs_json:
    description: "Path to ASVS coverage JSON"
    value: ${{ steps.finalize.outputs.asvs_json }}

  epss_json:
    description: "Path to EPSS findings JSON"
    value: ${{ steps.finalize.outputs.epss_json }}

runs:
  using: "composite"
  steps:
    - name: Prepare workspace
      shell: bash
      run: |
        set -euo pipefail
        REPORT_DIR="${{ inputs.report_dir }}"
        mkdir -p "${REPORT_DIR}/zap" "${REPORT_DIR}/governance" ".trivy-cache"
        rm -f "${REPORT_DIR}/gate_failed" || true

    # ---------------- SECRETS ----------------
    - name: Gitleaks (SARIF)
      shell: bash
      run: |
        set -euo pipefail
        REPORT_DIR="${{ inputs.report_dir }}"
        docker run --rm -v "$PWD:/repo" zricethezav/gitleaks:v8.21.0 \
          detect --source /repo \
          --config /repo/.gitleaks.toml \
          --report-format sarif \
          --report-path /repo/${REPORT_DIR}/gitleaks.sarif \
          --redact \
          --exit-code 0
        test -f "${REPORT_DIR}/gitleaks.sarif"

    - name: Gitleaks gate
      shell: bash
      run: |
        set -euo pipefail
        REPORT_DIR="${{ inputs.report_dir }}"
        python3 scripts/gitleaks_gate.py "${REPORT_DIR}/gitleaks.sarif"

    # ---------------- SAST ----------------
    - name: Bandit (JSON)
      shell: bash
      run: |
        set -euo pipefail
        REPORT_DIR="${{ inputs.report_dir }}"
        python3 -m pip install -q --upgrade pip bandit
        bandit -r app.py database.py auth.py ai_agent_deepseek.py \
          -f json -o "${REPORT_DIR}/bandit.json" || true
        test -f "${REPORT_DIR}/bandit.json" || echo '{"results":[]}' > "${REPORT_DIR}/bandit.json"

    - name: Bandit normalize (DefectDojo compatible)
      shell: bash
      run: |
        set -euo pipefail
        REPORT_DIR="${{ inputs.report_dir }}"
        python3 scripts/bandit_normalize.py \
          "${REPORT_DIR}/bandit.json" \
          "${REPORT_DIR}/bandit_dd.json"
        test -f "${REPORT_DIR}/bandit_dd.json" || echo '{"findings":[]}' > "${REPORT_DIR}/bandit_dd.json"

    - name: Semgrep scan (OWASP / ASVS)
      shell: bash
      run: |
        set -euo pipefail
        REPORT_DIR="${{ inputs.report_dir }}"
        docker run --rm -v "$PWD:/src" returntocorp/semgrep:1.75.0 \
          semgrep scan \
            --config p/owasp-top-ten \
            --config p/security-audit \
            --config p/python \
            --json \
            --output /src/${REPORT_DIR}/semgrep.json || true
        test -f "${REPORT_DIR}/semgrep.json" || echo '{"results":[]}' > "${REPORT_DIR}/semgrep.json"

    - name: Semgrep OWASP gate (baseline-aware)
      shell: bash
      run: |
        set -euo pipefail
        REPORT_DIR="${{ inputs.report_dir }}"
        BASELINE_DIR="${{ inputs.baseline_dir }}"
        if [ -f "${BASELINE_DIR}/semgrep-baseline.json" ]; then
          python3 scripts/semgrep_owasp_gate.py \
            "${REPORT_DIR}/semgrep.json" \
            "${BASELINE_DIR}/semgrep-baseline.json"
        else
          python3 scripts/semgrep_owasp_gate.py "${REPORT_DIR}/semgrep.json"
        fi

    # ---------------- SCA + EPSS/KEV ----------------
    - name: Trivy FS (rootless + cache-safe)
      shell: bash
      run: |
        set -euo pipefail
        REPORT_DIR="${{ inputs.report_dir }}"
        mkdir -p ".trivy-cache"
        docker run --rm \
          -u "$(id -u):$(id -g)" \
          -e TRIVY_CACHE_DIR=/tmp/trivy-cache \
          -v "$PWD:/work" \
          -v "$PWD/.trivy-cache:/tmp/trivy-cache" \
          aquasec/trivy:0.49.1 \
          fs /work \
          --severity HIGH,CRITICAL \
          --ignore-unfixed \
          --format json \
          -o /work/${REPORT_DIR}/trivy-sca.json
        test -f "${REPORT_DIR}/trivy-sca.json" || echo '{"Results":[]}' > "${REPORT_DIR}/trivy-sca.json"

    - name: EPSS + KEV gate
      shell: bash
      run: |
        set -euo pipefail
        REPORT_DIR="${{ inputs.report_dir }}"
        python3 scripts/epss_gate.py \
          --input "${REPORT_DIR}/trivy-sca.json" \
          --output "${REPORT_DIR}/epss-findings.json" \
          --threshold "${{ inputs.epss_threshold }}"
        test -f "${REPORT_DIR}/epss-findings.json" || echo '{"high_risk":[],"threshold":"'"${{ inputs.epss_threshold }}"'"}' > "${REPORT_DIR}/epss-findings.json"

    # ---------------- DAST (OPTIONAL) ----------------
    - name: Build app image (DAST)
      if: ${{ inputs.run_dast == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        docker build -t vuln-bank:ci -f containers/app/Dockerfile .

    - name: Start DAST stack
      if: ${{ inputs.run_dast == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        docker compose -f "${{ inputs.dast_compose_file }}" up -d

    - name: Wait for DAST readiness
      if: ${{ inputs.run_dast == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        for i in {1..20}; do
          curl -fs "${{ inputs.dast_url }}" >/dev/null 2>&1 && exit 0
          sleep 5
        done
        echo "[ERROR] DAST target not ready: ${{ inputs.dast_url }}"
        docker compose -f "${{ inputs.dast_compose_file }}" logs || true
        exit 1

    - name: ZAP Automation (DAST)
      if: ${{ inputs.run_dast == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        REPORT_DIR="${{ inputs.report_dir }}"
        chmod -R 777 "${REPORT_DIR}/zap" || true
        docker run --rm \
          --network vuln-bank_dastnet \
          -e TARGET_URL="${{ inputs.dast_url }}" \
          -v "$PWD/${REPORT_DIR}/zap:/zap/wrk" \
          -v "$PWD/security-policies/zap-automation.yml:/zap/automation.yml:ro" \
          ghcr.io/zaproxy/zaproxy:2.15.0 \
          zap.sh -cmd -autorun /zap/automation.yml
        test -f "${REPORT_DIR}/zap/zap_alerts.json"

    - name: ZAP severity gate
      if: ${{ inputs.run_dast == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        REPORT_DIR="${{ inputs.report_dir }}"
        python3 scripts/zap_severity_gate.py \
          "${REPORT_DIR}/zap/zap_alerts.json" \
          "${{ inputs.zap_fail_severity }}"

    - name: Stop DAST stack
      if: ${{ always() && inputs.run_dast == 'true' }}
      shell: bash
      timeout-minutes: 5
      run: |
        set -euo pipefail
        docker compose -f "${{ inputs.dast_compose_file }}" down || true

    # ---------------- ASVS (support no-DAST mode) ----------------
    - name: ASVS export (authoritative)
      shell: bash
      run: |
        set -euo pipefail
        REPORT_DIR="${{ inputs.report_dir }}"

        # If DAST is off, ensure zap file path doesn't break exporters that expect it.
        if [ "${{ inputs.run_dast }}" != "true" ]; then
          mkdir -p "${REPORT_DIR}/zap"
          test -f "${REPORT_DIR}/zap/zap_alerts.json" || echo '{"site":[]}' > "${REPORT_DIR}/zap/zap_alerts.json"
        fi

        python3 scripts/asvs_export.py \
          --tool-map schemas/asvs-tool-map.json \
          --semgrep "${REPORT_DIR}/semgrep.json" \
          --bandit "${REPORT_DIR}/bandit_dd.json" \
          --zap "${REPORT_DIR}/zap/zap_alerts.json" \
          --trivy "${REPORT_DIR}/trivy-sca.json" \
          --gitleaks "${REPORT_DIR}/gitleaks.sarif" \
          --out-json "${REPORT_DIR}/governance/asvs-coverage.json"

        test -f "${REPORT_DIR}/governance/asvs-coverage.json"

    # ---------------- FINALIZE OUTPUTS ----------------
    - id: finalize
      name: Finalize outputs
      shell: bash
      run: |
        set -euo pipefail
        REPORT_DIR="${{ inputs.report_dir }}"

        if [ -f "${REPORT_DIR}/gate_failed" ]; then
          echo "gate_failed=true" >> "$GITHUB_OUTPUT"
        else
          echo "gate_failed=false" >> "$GITHUB_OUTPUT"
        fi

        echo "asvs_json=${REPORT_DIR}/governance/asvs-coverage.json" >> "$GITHUB_OUTPUT"
        echo "epss_json=${REPORT_DIR}/epss-findings.json" >> "$GITHUB_OUTPUT"
