apiVersion: v1
kind: Secret
metadata:
  name: vuln-bank-db-client
  namespace: vuln-bank-app
type: Opaque
stringData:
  DB_NAME: "vulnerable_bank"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_HOST: "vulnbank-db.vuln-bank-db.svc.cluster.local"
  DB_PORT: "5432"
