#!/usr/bin/env python3
"""
GitHub Integration for EPSS/KEV Risk Findings:
- Auto-comment on PR
- Auto-create or update GitHub Issues per CVE
- Auto-close resolved Issues
- Auto-assign + auto-label severity
- Idempotent behavior

Requirements:
- GITHUB_REPOSITORY
- GITHUB_TOKEN
- EPSS_FINDINGS (JSON output from epss_gate.py)
"""

import os
import json
import urllib.request
import urllib.error

# -----------------------------------------------------
# Helpers
# -----------------------------------------------------

def load_json(path):
    """Safe loader."""
    if not os.path.exists(path):
        return None
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return None


def gh_api(url, method="GET", data=None, token=""):
    """Wrapper for GitHub REST API calls."""
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "EPSS-GH-Integration",
        "Authorization": f"Bearer {token}",
    }
    body = None
    if data is not None:
        headers["Content-Type"] = "application/json"
        body = json.dumps(data).encode()

    req = urllib.request.Request(url, headers=headers, method=method, data=body)

    try:
        with urllib.request.urlopen(req) as r:
            return json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        msg = e.read().decode()
        print(f"[ERROR] API {method} {url}: {msg}")
        return None
    except Exception as e:
        print(f"[ERROR] Unexpected API error: {e}")
        return None


# -----------------------------------------------------
# GitHub Operations
# -----------------------------------------------------

def get_existing_issues(repo, token):
    issues = gh_api(f"https://api.github.com/repos/{repo}/issues?state=open&per_page=100", token=token)
    if not issues:
        return []
    return issues


def find_issue_by_cve(issues, cve):
    for i in issues:
        if f"[{cve}]" in i.get("title", ""):
            return i
    return None


def create_issue(repo, token, v, assignee):
    title = f"[{v['cve']}] EPSS High-Risk Vulnerability"
    labels = [
        "security",
        f"severity-{v['severity'].lower()}",
    ]
    if v.get("is_kev"):
        labels.append("CISA-KEV")
    if v.get("epss", 0) >= 0.5:
        labels.append("EPSS-HIGH")

    body = (
        f"### High-risk vulnerability detected\n"
        f"**CVE:** {v['cve']}\n"
        f"**Package:** {v.get('pkg_name')}\n"
        f"**Installed:** {v.get('installed_version')}\n"
        f"**Fixed:** {v.get('fixed_version')}\n"
        f"**Severity:** {v.get('severity')}\n"
        f"**CVSS:** {v.get('cvss')}\n"
        f"**EPSS Score:** {v.get('epss')}\n"
        f"**Percentile:** {v.get('percentile')}\n"
        f"**KEV:** {v.get('is_kev')}\n"
        f"**Reasons:** {', '.join(v.get('reasons', []))}\n"
        f"---\n"
        f"Auto-generated by EPSS Gate."
    )

    data = {
        "title": title,
        "body": body,
        "labels": labels,
    }

    if assignee:
        data["assignees"] = [assignee]

    return gh_api(f"https://api.github.com/repos/{repo}/issues", method="POST", data=data, token=token)


def update_issue(repo, token, issue_number, body):
    return gh_api(
        f"https://api.github.com/repos/{repo}/issues/{issue_number}",
        method="PATCH",
        data={"body": body},
        token=token,
    )


def close_issue(repo, token, issue_number, comment="Resolved and auto-closed."):
    gh_api(
        f"https://api.github.com/repos/{repo}/issues/{issue_number}/comments",
        method="POST",
        data={"body": comment},
        token=token,
    )
    return gh_api(
        f"https://api.github.com/repos/{repo}/issues/{issue_number}",
        method="PATCH",
        data={"state": "closed"},
        token=token,
    )


def post_pr_comment(repo, pr_number, token, summary):
    data = {
        "body": summary
    }
    return gh_api(
        f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments",
        method="POST",
        data=data,
        token=token,
    )


# -----------------------------------------------------
# MAIN LOGIC
# -----------------------------------------------------

def main():
    repo = os.environ.get("GITHUB_REPOSITORY", "")
    token = os.environ.get("GITHUB_TOKEN", "")
    findings_path = os.environ.get("EPSS_FINDINGS", "")
    pr_number = os.environ.get("PR_NUMBER")

    if not repo or not token or not findings_path:
        print("[WARN] Missing environment variables for GH integration.")
        return

    findings = load_json(findings_path)
    if not findings:
        print("[INFO] No findings, skipping GH sync.")
        return

    high_risk = findings.get("high_risk", [])
    existing = get_existing_issues(repo, token)

    # -------------------------------------------------
    # Auto-comment PR
    # -------------------------------------------------
    if pr_number:
        summary = (
            f"### EPSS/KEV High-Risk Summary\n"
            f"Mode: **{findings.get('mode')}** | Threshold: **{findings.get('threshold')}**\n"
            f"Total High-Risk CVEs: **{len(high_risk)}**\n\n"
        )
        if high_risk:
            for v in high_risk:
                summary += f"- {v['cve']} (EPSS={v['epss']}, KEV={v['is_kev']})\n"
        else:
            summary += "No high-risk CVEs found.\n"

        post_pr_comment(repo, pr_number, token, summary)

    # -------------------------------------------------
    # Create/Update Issues
    # -------------------------------------------------
    active_cves = set()
    for v in high_risk:
        active_cves.add(v["cve"])

        issue = find_issue_by_cve(existing, v["cve"])
        assignee = os.environ.get("DEFAULT_ASSIGNEE", "")

        if issue:
            new_body = (
                f"### Updated high-risk CVE\n"
                f"**CVE:** {v['cve']}\n"
                f"**EPSS:** {v['epss']}\n"
                f"**Reasons:** {', '.join(v.get('reasons', []))}\n"
                f"---\n"
                f"Updated automatically."
            )
            update_issue(repo, token, issue["number"], new_body)
        else:
            create_issue(repo, token, v, assignee)

    # -------------------------------------------------
    # Auto-close stale Issues
    # -------------------------------------------------
    for i in existing:
        # Skip PR comments which also appear in issues API
        if "pull_request" in i:
            continue

        title = i.get("title", "")
        if "[" in title and "]" in title:
            cve = title.split("[")[1].split("]")[0].strip()
            if cve and cve not in active_cves:
                print(f"[INFO] Closing resolved CVE issue: {cve}")
                close_issue(repo, token, i["number"])

    print("[INFO] EPSS GitHub integration complete.")


if __name__ == "__main__":
    main()
