#!/usr/bin/env python3
"""
Auto-create GitHub Issues from EPSS findings.
Creates issues like:
  [CVE-2025-66418] EPSS High-Risk Vulnerability
"""

import os
import json
import urllib.request
import urllib.parse
import sys

GITHUB_API = "https://api.github.com"


def gh_request(method, url, token, payload=None):
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "User-Agent": "epss-github-bot",
    }

    data = None
    if payload:
        data = json.dumps(payload).encode("utf-8")

    req = urllib.request.Request(url, data=data, headers=headers, method=method)

    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            raw = resp.read().decode("utf-8")
            return json.loads(raw) if raw else {}
    except Exception as e:
        print(f"[ERROR] GitHub API {method} {url}: {e}", file=sys.stderr)
        return None


def issue_exists(repo, token, cve):
    query = urllib.parse.urlencode({
        "q": f'repo:{repo} "{cve}" in:title state:open'
    })
    url = f"{GITHUB_API}/search/issues?{query}"

    data = gh_request("GET", url, token)
    if not data:
        return False

    return data.get("total_count", 0) > 0


def severity_label(item):
    sev = item.get("severity", "").upper()
    cvss = float(item.get("cvss", 0))
    epss = float(item.get("epss", 0))

    if sev in ("CRITICAL", "HIGH") or cvss >= 9.0 or epss >= 0.7:
        return "severity-high"
    elif sev == "MEDIUM" or 6.0 <= cvss < 9.0:
        return "severity-medium"
    return "severity-low"


def build_body(item):
    cve = item["cve"]
    cvss = item.get("cvss")
    epss = item.get("epss")
    percentile = item.get("percentile")
    sev = item.get("severity")
    reasons = item.get("reasons", [])
    sources = ", ".join(item.get("sources", []))
    is_kev = item.get("is_kev", False)

    kev_status = "YES (CISA KEV)" if is_kev else "NO"

    return f"""
## EPSS High-Risk Vulnerability

**CVE:** `{cve}`
**Severity:** `{sev}`
**CVSS:** `{cvss}`
**EPSS:** `{epss}`
**EPSS Percentile:** `{percentile}`
**CISA KEV:** {kev_status}
**Sources:** {sources}

### Reasons
{chr(10).join(f"- {r}" for r in reasons)}

### References
- NVD: https://nvd.nist.gov/vuln/detail/{cve}
- EPSS Score: https://www.first.org/epss/score/{cve}
- CISA KEV Catalog: https://www.cisa.gov/known-exploited-vulnerabilities

---

### Required Actions
- [ ] Validate exposure in environment
- [ ] Apply patch/update
- [ ] Add regression tests
- [ ] Close after remediation

_Auto-generated by EPSS gate._
"""


def create_issue(repo, token, item):
    cve = item["cve"]

    if issue_exists(repo, token, cve):
        print(f"[INFO] Issue for {cve} already exists.")
        return

    title = f"[{cve}] EPSS High-Risk Vulnerability"
    body = build_body(item)
    sev_label = severity_label(item)

    labels = ["security", "epss", "auto-generated", sev_label]
    if item.get("is_kev"):
        labels.append("cisa-kev")

    payload = {"title": title, "body": body, "labels": labels}

    url = f"{GITHUB_API}/repos/{repo}/issues"
    resp = gh_request("POST", url, token, payload)

    if resp:
        print(f"[OK] Created issue #{resp.get('number')} for {cve}")


def main():
    epss_file = os.environ.get("EPSS_FILE", "security-reports/epss-findings.json")
    repo = os.environ.get("GITHUB_REPOSITORY")
    token = os.environ.get("GITHUB_TOKEN")

    if not repo or not token:
        print("[ERROR] Missing GitHub environment variables.", file=sys.stderr)
        sys.exit(1)

    if not os.path.exists(epss_file):
        print("[INFO] EPSS file not found, skipping.")
        sys.exit(0)

    with open(epss_file) as f:
        data = json.load(f)

    high_risk = data.get("high_risk", [])

    print(f"[INFO] High-risk CVEs: {len(high_risk)}")

    for item in high_risk:
        create_issue(repo, token, item)


if __name__ == "__main__":
    main()
