#!/usr/bin/env python3
"""
EPSS/KEV Dashboard Generator (Priority-Score-Optimized)

Inputs:
  - epss-findings.json    (generated by epss_gate.py)
Outputs:
  - site/index.html
  - site/cve.html
  - site/packages.html
  - site/kev.html
  - site/trends.html

Features:
  - Priority-score-driven dashboard
  - Top 10 CVEs by priority
  - CVSS vs EPSS bubble chart
  - Priority score histogram
  - Package risk aggregation
  - KEV-only high-risk table
"""

import json
from pathlib import Path
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd


INPUT_FILE = "security-reports/epss-findings.json"
SITE_DIR = Path("site")
SITE_DIR.mkdir(exist_ok=True)


# -------------------------------------------------------
# Load data
# -------------------------------------------------------
with open(INPUT_FILE, "r") as f:
    data = json.load(f)

records = data.get("high_risk", [])
df = pd.DataFrame(records)

if df.empty:
    df = pd.DataFrame(
        columns=[
            "cve",
            "pkg_name",
            "severity",
            "epss",
            "percentile",
            "cvss",
            "priority_score",
            "is_kev",
        ]
    )

df["cvss"] = df["cvss"].fillna(0.0)
df["priority_score"] = df["priority_score"].fillna(0.0)

# -------------------------------------------------------
# Helper to save HTML pages
# -------------------------------------------------------
def save_page(filename: str, body: str) -> None:
    html = f"""
    <html>
    <head>
        <title>Vuln Bank Risk Dashboard</title>
        <meta charset="utf-8" />
        <style>
            body {{
                font-family: Arial, sans-serif;
                margin: 20px;
            }}
            a {{
                margin-right: 20px;
            }}
            .card {{
                display: inline-block;
                padding: 15px;
                margin: 10px;
                border-radius: 8px;
                background: #f5f5f5;
                width: 260px;
                vertical-align: top;
            }}
            .value {{
                font-size: 26px;
                font-weight: bold;
            }}
            table {{
                border-collapse: collapse;
                width: 100%;
            }}
            th, td {{
                border: 1px solid #ccc;
                padding: 8px;
                text-align: left;
            }}
            th {{
                background: #eee;
            }}
        </style>
    </head>
    <body>
        <h2>Vuln Bank Risk Dashboard</h2>
        <a href="index.html">Home</a>
        <a href="cve.html">CVEs</a>
        <a href="packages.html">Packages</a>
        <a href="kev.html">CISA KEV</a>
        <a href="trends.html">Trends</a>

        <hr />
        {body}
    </body>
    </html>
    """
    (SITE_DIR / filename).write_text(html, encoding="utf-8")


# -------------------------------------------------------
# INDEX / HOME
# -------------------------------------------------------
top10 = df.sort_values("priority_score", ascending=False).head(10)

bar = px.bar(
    top10,
    x="cve",
    y="priority_score",
    color="severity",
    title="Top 10 CVEs by Priority Score",
)

hist = px.histogram(
    df,
    x="priority_score",
    nbins=20,
    title="Priority Score Distribution",
)

summary_html = f"""
<div class="card"><div class="value">{len(df)}</div>Total High-Risk Findings</div>
<div class="card"><div class="value">{df['priority_score'].max():.2f}</div>Highest Priority Score</div>
<div class="card"><div class="value">{df[df['is_kev']==True].shape[0]}</div>CISA KEV Findings</div>
"""

body = summary_html
body += "<h3>Top 10 Risk Findings</h3>"
body += bar.to_html(include_plotlyjs="cdn", full_html=False)
body += hist.to_html(include_plotlyjs=False, full_html=False)

save_page("index.html", body)


# -------------------------------------------------------
# CVE PAGE
# -------------------------------------------------------
bubble = px.scatter(
    df,
    x="cvss",
    y="epss",
    size="priority_score",
    color="severity",
    hover_data=["cve", "pkg_name", "priority_score"],
    title="CVSS vs EPSS (Bubble Size = Priority Score)",
)

table_html = df.sort_values("priority_score", ascending=False).to_html(index=False)

save_page(
    "cve.html",
    bubble.to_html(include_plotlyjs="cdn", full_html=False)
    + "<h3>All CVEs</h3>"
    + table_html
)


# -------------------------------------------------------
# PACKAGE PAGE
# -------------------------------------------------------
pkg_df = (
    df.groupby("pkg_name")
    .agg(
        max_priority=("priority_score", "max"),
        count=("cve", "count"),
    )
    .sort_values("max_priority", ascending=False)
)

pkg_bar = px.bar(
    pkg_df,
    x=pkg_df.index,
    y="max_priority",
    title="Package Risk (max priority score per package)",
)

save_page(
    "packages.html",
    pkg_bar.to_html(include_plotlyjs="cdn", full_html=False)
    + "<h3>Package Risk Table</h3>"
    + pkg_df.to_html()
)


# -------------------------------------------------------
# KEV-ONLY PAGE
# -------------------------------------------------------
kev_df = df[df["is_kev"] == True].sort_values("priority_score", ascending=False)

save_page(
    "kev.html",
    "<h3>CISA KEV High-Risk Findings</h3>" + kev_df.to_html(index=False)
)


# -------------------------------------------------------
# TRENDS PAGE (Historical)
# -------------------------------------------------------
# This page reads epss-history.jsonl if available
HISTORY_FILE = Path("security-reports/epss-history.jsonl")

if HISTORY_FILE.exists():
    rows = []
    with open(HISTORY_FILE, "r") as f:
        for line in f:
            try:
                rows.append(json.loads(line))
            except:
                pass
    hist_df = pd.DataFrame(rows)
else:
    hist_df = pd.DataFrame(columns=["timestamp", "epss_high_count", "kev_count"])

trend_chart = px.line(
    hist_df,
    x="timestamp",
    y=["epss_high_count", "kev_count"],
    title="EPSS/KEV Trend Over Time",
)

save_page(
    "trends.html",
    trend_chart.to_html(include_plotlyjs="cdn", full_html=False)
    + "<h3>Raw History</h3>"
    + hist_df.to_html()
)


print("[OK] Dashboard generated in /site/")
