#!/usr/bin/env python3
import os, json
from datetime import datetime, timezone

def load(path, default):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return default

score = load("docs/data/security-scorecard.json", {})
sla = load("docs/data/defectdojo-sla-weekly.json", {})
owasp_latest = load("docs/data/owasp-latest.json", {})

repo = score.get("repo", "unknown/unknown")
generated_at = score.get("generated_at") or datetime.now(timezone.utc).isoformat().replace("+00:00","Z")

s = score.get("score") or {}
overall, grade = s.get("overall"), score.get("grade")
owasp_s, epss_s, sla_s = s.get("owasp"), s.get("epss"), s.get("sla")

breaches = (sla.get("breaches") or {})
crit_b = int(breaches.get("Critical", 0) or 0)
high_b = int(breaches.get("High", 0) or 0)

epss = score.get("epss") or {}
epss_hr = int(epss.get("high_risk_count", 0) or 0)
top_cves = epss.get("top_cves") or []

owasp_counts = score.get("owasp") or (owasp_latest.get("counts") or {})
top_owasp = sorted([(k, int(v or 0)) for k,v in owasp_counts.items()], key=lambda x: x[1], reverse=True)[:5]

md = []
md.append(f"# Vuln Bank – Executive Security Summary")
md.append("")
md.append(f"- Repo: `{repo}`")
md.append(f"- Generated: `{generated_at}`")
md.append("")
md.append(f"## Security Scorecard")
md.append(f"- Overall: **{overall} ({grade})**")
md.append(f"- OWASP: **{owasp_s}** | EPSS: **{epss_s}** | SLA: **{sla_s}**")
md.append("")
md.append("## Key Risks (This Week)")
md.append(f"- SLA breaches: Critical={crit_b}, High={high_b}")
md.append(f"- EPSS high-risk count: {epss_hr}")
if top_cves:
    md.append("- Top EPSS CVEs:")
    for x in top_cves[:3]:
        md.append(f"  - `{x.get('cve')}` EPSS `{x.get('epss')}` package `{x.get('package')}`")
md.append("")
md.append("## OWASP Exposure (Top)")
for k,v in top_owasp:
    md.append(f"- {k}: {v}")
md.append("")
md.append("## Recommended Actions (Next 7 Days)")
md.append("- Triage and remediate all Critical SLA breaches; enforce fix-by dates.")
md.append("- For EPSS high-risk CVEs: patch/upgrade packages or mitigate via config/WAF rules.")
md.append("- Reduce A01/A02 exposure first (access control + crypto hygiene).")
md.append("")
md.append("## Notes")
md.append("- This summary is auto-generated by CI from GitHub labels + DefectDojo findings.")

os.makedirs("docs/data", exist_ok=True)
with open("docs/data/executive-summary.md", "w", encoding="utf-8") as f:
    f.write("\n".join(md))

# PDF generation (ReportLab)
os.makedirs("security-metrics/weekly", exist_ok=True)
try:
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas

    pdf_path = "security-metrics/weekly/executive-summary.pdf"
    c = canvas.Canvas(pdf_path, pagesize=letter)
    width, height = letter

    y = height - 60
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, "Vuln Bank – Executive Security Summary")
    y -= 24

    c.setFont("Helvetica", 10)
    for line in md[1:]:
        if y < 60:
            c.showPage()
            y = height - 60
            c.setFont("Helvetica", 10)
        # keep it one-page-ish; hard wrap simple
        c.drawString(50, y, line[:110])
        y -= 14

    c.save()
    print("[OK] executive-summary.md + executive-summary.pdf generated")
except Exception as e:
    print("[WARN] PDF not generated (missing reportlab?). Markdown generated.", e)
