#!/usr/bin/env python3
import json
import os
import sys
import requests

ZAP_JSON = os.getenv("ZAP_JSON", "security-reports/zap/zap_alerts.json")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
REPO = os.getenv("REPO")
RUN_ID = os.getenv("RUN_ID")

if not GITHUB_TOKEN or not REPO:
    print("[SKIP] Missing GitHub context")
    sys.exit(0)

if not os.path.exists(ZAP_JSON):
    print("[SKIP] ZAP report not found")
    sys.exit(0)

headers = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json"
}

with open(ZAP_JSON) as f:
    data = json.load(f)

alerts = data.get("site", [{}])[0].get("alerts", [])

def is_a01_a02(alert):
    owasp = alert.get("owasp", "")
    risk = alert.get("riskcode")
    conf = alert.get("confidence")

    return (
        owasp in ["A01", "A02"]
        and risk == "3"        # High
        and conf == "3"        # High
    )

critical = [a for a in alerts if is_a01_a02(a)]

if not critical:
    print("[OK] No A01/A02 High-High findings")
    sys.exit(0)

title = "🚨 INCIDENT: OWASP A01/A02 High Risk Detected"
labels = ["incident", "security", "owasp:A01/A02", "risk:high"]

# Check existing issues
issues_url = f"https://api.github.com/repos/{REPO}/issues"
existing = requests.get(issues_url, headers=headers).json()

for issue in existing:
    if issue.get("title") == title and issue.get("state") == "open":
        print("[SKIP] Incident already exists")
        sys.exit(0)

body_lines = [
    "## 🚨 Security Incident Detected",
    "",
    f"**Repository:** `{REPO}`",
    f"**Run ID:** `{RUN_ID}`",
    "",
    "### Findings:"
]

for a in critical:
    body_lines.append(
        f"- **{a.get('name')}** | OWASP `{a.get('owasp')}` | "
        f"URL: `{a.get('url')}`"
    )

body_lines.append("")
body_lines.append("_Auto-generated by DevSecOps pipeline_")

payload = {
    "title": title,
    "body": "\n".join(body_lines),
    "labels": labels
}

resp = requests.post(issues_url, headers=headers, json=payload)

if resp.status_code >= 300:
    print("[ERROR] Failed to create incident:", resp.text)
    sys.exit(1)

print("[INCIDENT] GitHub issue created successfully")
